apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: api-port
      protocol: TCP
      port: 5001
      targetPort: 5000
    - name: socket-port
      protocol: TCP
      port: 1979
      targetPort: 1978
  selector:
    app: api
