apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: api-secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: api-secret
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: api-secret
          image: fairuztahir/qp-api
          imagePullPolicy: Always
          name: api
          ports:
            - name: api-port
              containerPort: 5000
            - name: socket-port
              containerPort: 1978
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - mountPath: /app
              name: api-data
            - mountPath: /uploads/images
              name: tmp
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: api-data
        - name: tmp
          persistentVolumeClaim:
            claimName: tmp
