apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goredis
  name: goredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goredis
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: goredis
    spec:
      containers:
        - env:
          - name: MASTER
            value: "true"
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                key: REDIS_PASS
                name: redis-secret
          image: redis:6.0.8-alpine
          name: goredis
          args: ["--requirepass", "$(REDIS_PASS)"]
          ports:
            - name: redis-port
              containerPort: 6379
      restartPolicy: Always
