apiVersion: v1
kind: Secret
metadata:
  name: fai-secret
data:
  POSTGRES_USER: ZmFpcnV6dGFoaXI=
  POSTGRES_PASSWORD: ZmFpcnV6dGFoaXI=
  POSTGRES_DB: Z29icF9kYg==
  PGADMIN_DEFAULT_EMAIL: bW9oZGZhaXJ1enRhaGlyQGdtYWlsLmNvbQ==
  PGADMIN_DEFAULT_PASSWORD: ZmFpcnV6dGFoaXI=
  PGADMIN_LISTEN_PORT: NTQ1NA==