version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ../
      dockerfile: ./docker/web.Dockerfile
    image: ${PROJECT_ID}/sanicvue-web:${VERSION}
    environment:
      VUE_APP_I18N_LOCALE: ${VUE_APP_I18N_LOCALE}
      VUE_APP_I18N_FALLBACK_LOCALE: ${VUE_APP_I18N_FALLBACK_LOCALE}
    depends_on:
      - sanicbe
    tty: true
    networks:
      - webnet

  sanicbe:
    container_name: sanicbe
    build:
      context: ../
      dockerfile: ./docker/sanicbe.Dockerfile
    image: ${PROJECT_ID}/sanicvue-be:${VERSION}
    depends_on:
      - pgadmin
    tty: true
    networks:
      - webnet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    networks:
      - webnet

  redis:
    container_name: redis
    image: redis:6.2-alpine
    networks:
      - webnet

  db:
    container_name: db
    image: postgres:14-alpine
    networks:
      - webnet

  proxy:
    container_name: proxy
    build:
      context: ../
      dockerfile: ./docker/proxy.Dockerfile
    image: ${PROJECT_ID}/sanicvue-proxy:${VERSION}
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
