apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: fairuztahir/qp-web
          imagePullPolicy: Always
          name: web
          ports:
            - name: ui-port
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - mountPath: /app
              name: web-data
            - mountPath: /app/node_modules
              name: node-modules
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: web-data
        - name: node-modules
          persistentVolumeClaim:
            claimName: node-modules
